# 指定语言环境
language: node_js

node_js:
  - node

 #指定只有检测到master分支有变动时才执行任务
branchs:
  only:
  - master

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
  - $HOME/.npm

before_install:
  - cd /bin
  - sudo wget https://github.com/leancloud/lean-cli/releases/latest/download/lean-linux-x64
  - sudo mv lean-linux-x64 lean
  - sudo chmod -R 755 /bin/lean
  - cd -

install:
  - yarn

# cache: 
#   - yarn

script:
  - yarn build

aftersuccess: 
  - lean login -u $LC_USER -p $LC_PASSWORD -r CN
  - lean switch SMC
  - lean deploy
  - lean publish

deploy:
  - provider: surge
    skip_cleanup: true
    project: dist/client
    domain: smcv.surge.sh
  - provider: surge
    skip_cleanup: true
    project: dist/client
    domain: smcc.surge.sh
  - provider: surge
    skip_cleanup: true
    project: dist/client
    domain: smc-cn.surge.sh
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    local_dir:  dist/client
    # keep_history: true
    on:
      branch: master
    # fqdn: smc.wiki