export default {
	speakersList: [],
	volumeSlider: 50,
	speedSlider: 2,
	te: null,
	music_volume: null,
	content: '',
	sliderScale: 100,
	currentProgress: 0,
	currentPlayUrl: '',
	slideIndex: null,
	tabIndex: null,
	prevSpeaker: null,
	segmentMD5: null,
};
